# Generated by Django 4.1.4 on 2022-12-27 11:37

from django.db import migrations

import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', shop.models.UserManager()),
            ],
        ),
    ]
